---
title:               ccollins
tagline:             Hi, I'm Chandler. Follow me as I live my life and share all of the interesting things that I find along the way.
login:               ccollins
password:            monkey97A
name:                Chandler Collins
twitter:             chanman_82
github:              https://github.com/chanman82
email:               address@example.com
google_analytics_id: YOUR_GA_ID
